### ISSUE TITLE
cuvid: Failed cuvidCreateDecoder 2 (CUDA_ERROR_OUT_OF_MEMORY)

### ISSUE THREAD

**Issue by noblemd00** [Nevcairiel/LAVFilters#99]
Error Encoding using NVEncC 2.07v2 x64

Encoding using NVEncC 2.07v2 x64 failed with exit code: 1 (0x1)

The exit code might be a system error code: STATUS_WAIT_1

The exit code might be a system error code: Incorrect function.

cuvid: Failed cuvidCreateDecoder 2 (CUDA_ERROR_OUT_OF_MEMORY)
failed to init decoder.

StaxRip.ErrorAbortException: Encoding using NVEncC 2.07v2 x64 failed with exit code: 1 (0x1)

The exit code might be a system error code: STATUS_WAIT_1

The exit code might be a system error code: Incorrect function.

cuvid: Failed cuvidCreateDecoder 2 (CUDA_ERROR_OUT_OF_MEMORY)
failed to init decoder.

   at StaxRip.Proc.Start() in D:\Projekte\VS\VB\StaxRip\General\Proc.vb:line 240
   at StaxRip.NVIDIAEncoder.Encode() in D:\Projekte\VS\VB\StaxRip\Encoding\NVIDIAEncoder.vb:line 80
   at StaxRip.MainForm.Encode() in D:\Projekte\VS\VB\StaxRip\Forms\MainForm.vb:line 2220
   at StaxRip.MainForm.RunJobRecursive() in D:\Projekte\VS\VB\StaxRip\Forms\MainForm.vb:line 3462

[Wayward.Pines.test_new_StaxRip.log.txt](https://github.com/Nevcairiel/LAVFilters/files/375916/Wayward.Pines.test_new_StaxRip.log.txt)

**Comment by Nevcairiel** [comment]
This is the wrong project.
